### ISSUE TITLE
Implement IUserSecurityStampStore

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-forsaken#154]
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/818#issuecomment-175117869

**Comment by rcyq** [comment]
This issue seems to be completed? See [AbpUserStore.cs](https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs)

**Comment by hikalkan** [comment]
Yes, it's done for Identity Core (Abp.ZeroCore). Let this issue remain open, maybe it's implemented for Identity 2.x too :)
