### ISSUE TITLE
Should not store entities in the cache

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-forsaken#172]
Since it causes to serialization/deserialization problems.

**Comment by emaish** [comment]
What should we store i cache ? :)

**Comment by hikalkan** [comment]
Specialized cache objects :)

Entities are not well BINARY serializable/deserializable since they ara actually EF proxy objects. But you can serialize to JSON string and deserialize from JSON string for example if you really need it.

**Comment by emaish** [comment]
Dtos or List of Dtos for example ?

**Comment by hikalkan** [comment]
Yes, they are good candidates for example. Also, do not refresh cache if your entities changed by some other source (you may use entity change event of eventbus).

Remember:

"There are only two hard things in Computer Science: cache invalidation and naming things."

Phil Karlton
