### ISSUE TITLE
Permission & Role that depend on an object Id

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/module-zero-forsaken#187]
It will be great to have a permission and role that's for a subset of objects. For example, The Author may have Owner Role on Article X and Y and not Z. These permissions and Roles I can add or remove.

**Comment by hikalkan** [comment]
Thank you for your suggestion. it requires much change but this would be great feature. We will definetely consider it.

**Comment by guilmori** [comment]
Also was asked on the forum.
http://forum.aspnetboilerplate.com/viewtopic.php?f=3&t=949&p=3254#p3254

**Comment by TerryBentley** [comment]
We have need of this feature in our current project. Do you know if/when you will add this feature as I will then know if I have to write my own version?

**Comment by hikalkan** [comment]
Hi,

It will not be in a short time since we have other higher priorities. I suggest you to extend it yourself if you can.

Have a nice day.

**Comment by Caskia** [comment]
+1

**Comment by junghandy** [comment]
+1
