### ISSUE TITLE
Salted hash password

### ISSUE THREAD

**Issue by stromsky** [aspnetboilerplate/module-zero-forsaken#19]
I could be wrong, but it seems that current implementation does not use salted hash for storing passwords. It would be nice security enhancement to have in module-zero.

**Comment by hikalkan** [comment]
Hi,

We're using ASP.NET Identity's PasswordHasher for that. You mean module-zero force us to use salted hash?

**Comment by stromsky** [comment]
Hi,

I did hasty conclusion based on what I've seen in the database. There were initially 3 users created in database table with exactly the same hashed password. But now I see that this hash is hard-coded in Configuration.cs. You can cancel this issue.

PS: Thanks for your effort on this great project.
