### ISSUE TITLE
AbpZeroDbMigrator isn't compatible with EntityFramework.MappingAPI (required for 'EntityFramework.BulkInsert' package)

### ISSUE THREAD

**Issue by 4nonym0us** [aspnetboilerplate/module-zero-forsaken#206]
### Exception

Exception thrown: 'EntityFramework.MappingAPI.Exceptions.ParentNotMappedYetException' in EntityFramework.MappingAPI.dll after the `Context.BulkInsert(data);` method call.
### Stacktrace

`в EntityFramework.MappingAPI.Mappers.CodeFirstMapper.PrepareMapping(String typeFullName, EdmType edmItem) in c:\dev\EntityFramework.MappingAPI\trunk\src\EntityFramework.MappingAPI\Mappers\CodeFirstMapper.cs:line 51`
Source: https://github.com/kjbartel/efmappingapi/blob/master/src/EntityFramework.MappingAPI/Mappers/CodeFirstMapper.cs#L51
### Note

`Update-Database` works fine with both MappingAPI and BulkInsert.

**Comment by hikalkan** [comment]
Hi,

I did not know this MappingAPI thing. It seems a useful tool.

We created AbpZeroDbMigrator to help you to migrate more than one database. For database per tenant approach, you may have hundreds of database and it will be very hard to migrate them one by one.
If this tool does not work, you can always use EF's migrate.exe or Update-Database command, as you know.

When it comes to AbpZeroDbMigrator, I don't know why it don't work with EntityFramework.MappingAPI. AbpZeroDbMigrator's code is very simple actually (https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbMigrator.cs#L59)
It just uses EF's standard MigrateDatabaseToLatestVersion class as can be seen in the code.
Is there any other way that will be compatible with MappingAPI tool?

**Comment by 4nonym0us** [comment]
Hi,
I use https://efbulkinsert.codeplex.com/ and it depends on the MappingAPI. EfBulkInsert has extremely good performance, just check this out:
![image](https://cloud.githubusercontent.com/assets/2701409/15626886/d3e54bec-24d9-11e6-9aae-10fb7d96d26a.png)
I guess that even a standalone MappingAPI package can be used by developers in some complicated Seed methods.

I saw that AbpZeroDbMigrator uses method `MigrateDatabaseToLatestVersion` and I also thought that method should works in the same was as `Update-Database` command.

I assume that exception is thrown because database is being initialized only when context is used first time. If so, maybe we should force the process by calling method `dbContext.Object.Database.Initialize(bool force)`.

Documentation for this method.
```
    /// <summary>
    /// Runs the the registered <see cref="T:System.Data.Entity.IDatabaseInitializer`1"/> on this context.
    ///             If "force" is set to true, then the initializer is run regardless of whether or not it
    ///             has been run before.  This can be useful if a database is deleted while an app is running
    ///             and needs to be reinitialized.
    ///             If "force" is set to false, then the initializer is only run if it has not already been
    ///             run for this context, model, and connection in this app domain. This method is typically
    ///             used when it is necessary to ensure that the database has been created and seeded
    ///             before starting some operation where doing so lazily will cause issues, such as when the
    ///             operation is part of a transaction.
    /// 
    /// </summary>
    /// <param name="force">If set to <c>true</c> the initializer is run even if it has already been run.
    ///             </param>
    public void Initialize(bool force)
    {
      if (force)
      {
        this._internalContext.MarkDatabaseInitialized();
        this._internalContext.PerformDatabaseInitialization();
      }
      else
        this._internalContext.Initialize();
    }
```

I'm going to check whether my assumptions are correct and I will report in if I find a solution.

**Comment by 4nonym0us** [comment]
Tested few different scenarios and none of them fixed an error.
After some debugging I can say only that exception is thrown when MappingAPI prepares mapping for table `AbpPermissions` with following parameters:
_typeFullName_: `Abp.Authorization.Users.UserPermissionSetting`
_edmItem_: `MyProject.EntityFramework.UserPermissionSetting`
Method tries to determine the parent EntityMap for the EdmItem but fails to do that because it can't find base type (which is `MyProject.EntityFramework.PermissionSetting`).
`PrepareMapping` is the method where pure magic occurs as when exception is thrown, EntityMap list contains only a few Abp-related maps:

1. **Abp.Auditing.AuditLog**
2. **Abp.BackgroundJobs.BackgroundJobInfo**
3. **Abp.Authorization.Users.UserLogin**

All of the rest entity maps are my domain layer entities.

Does anyone have any thought on this?

**Comment by hikalkan** [comment]
I haven't understand why MyProject.EntityFramework.UserPermissionSetting is edmItem. UserPermissionSetting entity is defined in Abp.Zero assembly.
