### ISSUE TITLE
Advanced  functions for Zero

### ISSUE THREAD

**Issue by AlexGeller** [aspnetboilerplate/module-zero-forsaken#209]
Hi,

I have two functions required for Zero.
First, Tanant with admin role can login to his User's Account. 
Second, Regular User can set another user account as his agent with agent roles which have permission definitions, so agent user can login to the regular user.
Do you think those two functions is possible to implement?

Thank you.

**Comment by 4nonym0us** [comment]
@AlexGeller ,
According to the [AspNetZero official site](http://www.aspnetzero.com/), there is `User and Tenant impersonation` and I'm not sure that Halil was going to move this feature from AspNetZero to AbpZero.

**Comment by hikalkan** [comment]
Yes, AspNet Zero has two matching features:

* User impersonation allows admin to login as other users.
* User linking allows you to link 2 or more users and switch between these accounts without entering password.

You can try it by creating a demo: http://www.aspnetzero.com/

So, these are all possible. Also, I have shared impersonation in a Gist before: https://gist.github.com/hikalkan/8862d9f7ae8b4874976d
