### ISSUE TITLE
Make UserRole abstract

### ISSUE THREAD

**Issue by abou-emish** [aspnetboilerplate/module-zero-forsaken#258]
Dear @hikalkan ,

i want to make custom implementation for PermissionChecker where i have GroupUserRole inherit UserRole and add property GroupId to check if permission is granted against RoleId and GroupId.

So UserRole should be abstract and can be inherited in our projects, it will be usefull for the following reasons
1- UserPermissionCachInvalidator will still be usable with my GroupUserRole because it will handle UserRoleBase not UserRole

2- To allow add more properties to UserRole (ex: GroupId property) and still use the same repository and avoid entityframework Discriminator

what do you think ?

**Comment by emaish** [comment]
i updated my text above, please check

**Comment by hikalkan** [comment]
Hi,

Making UserRole abstract requires some other classes should be abstract (like AbpZeroDbContext, UserStore and maybe others). I understand why you need it, but any other developer may need similar thing for other entity types. I personally don't want to make any other entity abstract. We should think another solution for such requirements. I have no time to think it deeply right now. So, it will be better to you think a solution first. If you can not find any way, please write again to think we together.

**Comment by emaish** [comment]
Your efforts are appreciated, for now i implemented a solution that works for me, it's not the best but it works with current design of UserRole.
To know, i go deep in Abp Authorization code and i found that it need some changes to be flexible with custom permissions, when i have time and install Visual Studio 2015 i will suggest some enhancements.
Thank you
