### ISSUE TITLE
 Secure Web API using API Key Authentication – HMAC Authentication

### ISSUE THREAD

**Issue by abou-emish** [aspnetboilerplate/module-zero-forsaken#265]
here is an [article](http://bitoftech.net/2014/12/15/secure-asp-net-web-api-using-api-key-authentication-hmac-authentication/) describing how to do it

**Comment by hikalkan** [comment]
It's too long :)
Does ABP prevents to implementing that? Or you want to include this to ABP as default?

**Comment by emaish** [comment]
i want ABP to have it by default, the framework needs this feature :)

**Comment by hikalkan** [comment]
At first look, it does not seems common for most projects. But I will give a deeper look.

**Comment by emaish** [comment]
It's required for projects that call the APIs from clients such as mobile applications or website hosted separately and want to use Antiforgery.

I suppose if I want to use Antiforgery from remote clients, I need to limit the calls to MVC and Web APIs with API key, is that right?!

**Comment by hikalkan** [comment]
As I know, antiforgery is just for browser clients since it's only problem in browsers.
For mobile clients for example, token based auth can be used.
As I said, I should check the article deeper to understand why it's needed.

**Comment by psyvision** [comment]
I have implemented HMAC for my ABP based web site / api.  We need to call it from windows services but we also use it for web app to web app communication.

**Comment by emaish** [comment]
Can you share your code ? :)

**Comment by psyvision** [comment]
I've put together a quick Gist here:

https://gist.github.com/psyvision/406eb547f60a73fe97ced39b2215e5ca

Essentially:

1. There is a Public and Private Hash added to the AbpUser table (I also have a CanUseWebApi flag as we dont want all users using it).
2. There is a MyApp.Hmac assembly that provides signing / validation handlers.
3. There is an Auth attribute that can then be put on controllers to validate the incoming request using HMAC.
4. The PostData.cs file demonstrates calling the Api via an application/service.

Certain parts could probably be tweaked to fit the ABP framework better - but it meets the needs of our App as it is.
