### ISSUE TITLE
Not able to use in my project too much dependencys

### ISSUE THREAD

**Issue by sergy79** [aspnetboilerplate/module-zero-forsaken#270]
Implementing the modules zero features should be easier, in documentation it shows much code dependency on filters and services.

Please separate and make easy

Please update documentation on what I need to remove for simpler project ASP MPA

**Comment by Worthy7** [comment]
The documentation is actually out of date now for MZ, I just started to implement it myself and it isn't correct in quite a few ways. I suggest downloading a template instead form the home page with MZ on it, and copying the code form there instead of from the explanation in the documentation.
