### ISSUE TITLE
Can add the group?

### ISSUE THREAD

**Issue by unreal0** [aspnetboilerplate/module-zero-forsaken#284]
Can add the group? each group has its own permissions, Group founders have admin permissions group (management team members, such as whether to allow an applicant to join, blacklisted, etc), other members join and leave the permissions

**Comment by maliming** [comment]
Role does not solve your problem?

**Comment by unreal0** [comment]
whether role only assigned to  users Instead of group or organizational unit?
One group received a single role group members automatically receive the appropriate permissions, such as with administrative privileges, the founder, other members have their own corresponding permission less than founder (with). user permissions for this permission and his different. is independent of the permissions

**Comment by hikalkan** [comment]
We havent thought such a group approach before. I'm not sure if it's general enough to be a part of the framework. Maybe it's a special system for your own application. Do you know any system implements (or document describes) such a group structure so we can check it as a reference implementation?

**Comment by unreal0** [comment]
I think he should is General, certainly some system not need, can will it as alternative function. such of case many (from China Tencent company of QQ and weixin social software, some Community system wants to built a coterie, invited several people, with tourism and so on, a company of employees, in this sector has a permission, for a sector this permission is disappeared has, is has other permission)
This is discussed in detail:
[group-vs-role-any-real-difference](http://stackoverflow.com/questions/7770728/group-vs-role-any-real-difference)

**Comment by hikalkan** [comment]
Hi,

From the SO question:

> Recently, I've come across an administration software, where is a bunch of users. Each user can have assigned a module (whole system is split into a few parts called modules ie. Administration module, Survey module, Orders module, Customer module). On top of it, each module have a list of functionalities, that can be allowed or denied for each user. So let's say, a user John Smith can access module Orders and can edit any order, but haven't given a right to delete any of them.

> If there was more users with the same competency, I would use a group to manage that. I would aggregate such users into the same group and assign access rights to modules and their functions to the group. All users in the same group would have the same access rights.

This is exactly how roles works for module zero. Roles are used to group permissions (aka access rights).

On the other hand, module-zero has "Organization Units" which can be used to group users and other objects, so users can perform certain operations on related objects (see http://www.aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units).

**Comment by unreal0** [comment]
Can  zero achieve the following functions?
###GroupRole
GR1: { 'create' }
GR2: { 'block' }
GR3: { 'delete' }
GR4: { 'received' }
GR5: { 'send' }
GR6: { 'view' }
GRC(GroupRoleCommon):{  'GR4', 'GR5', 'GR6' }
###user
u1.create('group1'): 
	t1(creater): auto-assigned  GRC + GR1 + GR2+ GR3
	t2(join): auto-assigned  GRC
	t3(join): auto-assigned  GRC + GR3(t1 manual-assigned GR3 or some buseness rules )
	t4(join): auto-assigned  GRC + GR3(t1 manual-assigned GR3 or some buseness rules ) ==> (blocked by t1 )changed to GR6
u2.create('group1') or u1.create('group2'): Automatically copy the above template
u1.create('group1-sub-group3') : Still not ready

**Comment by hikalkan** [comment]
I'm not sure understood it exactly, but roles has not an inheritance feature. But you can assign more than one role to a user, and also add/remove specific permissions to/from a single user.
Current OUs (can be considered as like to groups) has no permission relation. If has inheritance, but it's used to filter/restrict data rather than functionality.
So, I think it's not what you want.

**Comment by unreal0** [comment]
I hope that zero can improve the function
