### ISSUE TITLE
Dependency Optimizations

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-forsaken#288]
See

* https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1528
* https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1749

**Comment by viewtance** [comment]
This issue still not be resolved?
Performance issue should be assigned to the high priority, customers already complained our project which developed based on ZERO performance is slowly.

**Comment by ismcagdas** [comment]
Hi @viewtance,

We will work on this problem for 2.2 release in this week or next week.

**Comment by hikalkan** [comment]
I tested Resolve duration for UserManager, RoleManager and a simple class without a dependency. Loop count is **10,000**. Results:

````
Resolve<UserManager>: 17992.822
Resolve<RoleManager>: 3741.358
Resolve<PlainClass>: 46.900
````

So, resolving an instance of UserManager takes 1.8 milliseconds, RoleManager takes 0.37 milliseconds and a most simple empty class takes 0.0047 milliseconds.

In the other words, We can create 555 UserManager in 1 second.
