### ISSUE TITLE
NHibernate filters and AbpZero don't seem to work

### ISSUE THREAD

**Issue by bogeydude** [aspnetboilerplate/module-zero-forsaken#292]
Hi Kalkan,
I'm trying to get AbpZero running with NHibernate. All goes well except for tenant filtering in a multitenancy database. Somehow this feature doesn't work: filters don't get applied which of course leads to errors. For instance when I try to login and try to find the user the MayHaveTenantFilter doesn't get set and the query comes up with the first user with the given name (if a username is used for multiple tenants)

````C#
using (_unitofWorkManager.Current.SetTenantId(oTenantId))
{
   var user = await _userManager.AbpStore.FindByNameOrEmailAsync(userNameOrEmailAddress);
}
````

Any ideas?

**Comment by hikalkan** [comment]
I should check this.

**Comment by hikalkan** [comment]
Have you derived your Entity mapping class from ``EntityMap<TEntity,TPrimaryKey>``?

**Comment by bogeydude** [comment]
Yes, they are: 
`public class UserMap : EntityMap<User, long>`

**Comment by WtbtBD** [comment]
I have a solution，but Is not very good，My each `Map`，Add `ApplyFilter<TFilter>() ` Again，this feature is work。I don‘t know why？Please don't mind my bad English.
