### ISSUE TITLE
Foreign key relationship not generated for some audited entities

### ISSUE THREAD

**Issue by denisvirissimo** [aspnetboilerplate/module-zero-forsaken#328]
I've notice that some entities (e.g. BackgroundJobs, Features, Editions) in Module Zero do not have foreign key generated in migrations for the User Id (creator, deleter, modifier) of Audited class. As a consequence, there is no referential integrity in the database. 
Is there any reason for the boilerplate being like this?

**Comment by hikalkan** [comment]
In current design, it would be fine to add foreign keys actually. There is no good reason actually. Add your own database if you like. We consider this for future versions. Thanks.
