### ISSUE TITLE
Exception thrown: 'System.IO.FileLoadException' in System.Net.Http.dll

### ISSUE THREAD

**Issue by gijswijs** [aspnetboilerplate/module-zero-forsaken#334]
I get en error thrown when I call this endpoint  /api/TokenAuth/ExternalAuthenticate

System.IO.FileLoadException: 'Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

![image](https://cloud.githubusercontent.com/assets/7912094/24459553/6bd24236-14ce-11e7-90f1-054db744bb41.png)

It looks an awful lot like this problem, but that solution didn't work for me:
https://stackoverflow.com/questions/41550563/system-net-http-nuget-package-4-3-0-reference-generates-system-io-fileloadexcept

**Comment by hikalkan** [comment]
This is a bug of System.Net.Http 4.3.0. Move to 4.3.1 (see https://github.com/aspnet/JavaScriptServices/issues/487#issuecomment-282143521) for your project (explicitly add this package). It worked for me.

**Comment by gijswijs** [comment]
@hikalkan Did you add it to a specific project, or to every project?

**Comment by hikalkan** [comment]
To the startup (web) project.
