### ISSUE TITLE
AbpUser Custom problem

### ISSUE THREAD

**Issue by apchenjun** [aspnetboilerplate/module-zero-forsaken#339]
In my project user data I need more fields and Surname FullName Phone Email these fields can be empty in abpuser class these fields cannot be empty how should I configure

**Comment by hikalkan** [comment]
You can extend User class (just add new properties to your User class in your project).
You can also change mapping of existing properties using EF fluent mapping in onmodelcreating.

**Comment by rqx110** [comment]
Reference #337
