### ISSUE TITLE
Return 401 Unauthorized from ASP.NET Core API

### ISSUE THREAD

**Issue by laozhuorun** [aspnetboilerplate/module-zero-forsaken#349]
After I upgrade my application to  Module-Zero 2.0.1，
i access every webapi (which need authorizeon) on swagger ui，
it  return  404  and  redirect to 'Accout/Login'（it was return 401 and message "The current user is not logged in" on 1.5.1）
eg：“http://localhost:22742/Account/Login?ReturnUrl=%2Fapi%2Fservices%2Fapp%2FCaching%2FClearCache”。
     i think this problem is cause by AspNetCore.Identity replace AspNet.Identity.Core，
how cound i get 401 result again with a unauthorized request

**Comment by hikalkan** [comment]
Hi,

Actually, it's not replaced. Abp.Zero package still works with old AspNet.Identity.Core (v2.x) and we introduced a new package, Abp.ZeroCore which uses new Microsoft.AspNetCore.Identity 1.x.
So, if you just upgraded nuget packages, it should not be changed.
