### ISSUE TITLE
Table Not Exists

### ISSUE THREAD

**Issue by ghost** [aspnetboilerplate/module-zero-forsaken#388]
1- In Abp.Authorization.Roles : 
[Table("AbpRoleClaims")]
    public class RoleClaim : CreationAuditedEntity<long>, IMayHaveTenant .....

But table not exists.

2- In Abp.Authorization.Users:
[Table("AbpUserTokens")]
    public class UserToken : Entity<long>, IMayHaveTenant
    
but table not exists.

3- In Abp.IdentityServer4:
[Table("AbpPersistedGrants")]
    public class PersistedGrantEntity : Entity<string>

but table not exists.

**Comment by acjh** [comment]
Did you add DbSet properties in your DbContext?

**Comment by hikalkan** [comment]
These are in Abp.ZeroCore package (this is for ASP.NET Core Identity 1.x). If you are usin Abp.Zero package (this is for ASP.NET Identity 2.x) then these entities are not available for you.
