### ISSUE TITLE
Enhancement request: CORS configuration

### ISSUE THREAD

**Issue by lamuertepeluda** [aspnetboilerplate/module-zero-forsaken#391]
Hi there,

could you do something to make CORS configuration easier, e.g. like [this nice Express JS middleware](https://github.com/expressjs/cors#configuration-options)?

It's a feature we miss a lot and causes much pain each time we want to make a SPA which is hosted somewhere else from our ASP.NET Zero backend (especially when developing) due to the diffculty of implementing a reflect origing or dynamic whitelist behavior.

Thanks

**Comment by hikalkan** [comment]
Hi,

I believe this should be a part of ASP.NET framework. You can create a feature/enhancement request to https://github.com/aspnet/Security/issues/new

**Comment by lamuertepeluda** [comment]
Hi,

I think it's not impossible to do this kind of whitelisting using pure ASP.NET framework. 
My point is if ASP.NET Zero could ship with a simpler configuration or a middleware for doing this task, e.g. as simple as the above mentioned middleware for Express JS, as added value for this framework.

References:

* https://stackoverflow.com/questions/17323350/access-control-allow-origin-with-multiple-domains
* https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api
* https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by hikalkan** [comment]
This can also be an independent open source library. Anyway, I added this to backlog to evaluate for future versions. Thanks.
