### ISSUE TITLE
aspnetboilerplate - User Session in web api using token based authentication 

### ISSUE THREAD

**Issue by Noushida** [aspnetboilerplate/module-zero-forsaken#401]
In normal web api,   I am getting user info and ClaimsIdentity using custom authorization filter   by header authorization token,
 string token = filterContext.Request.Headers.GetValues("Authorization").First();
                    var accessToken = token.Replace("Bearer ", "");
                    var userInfoClient = new UserInfoClient(new Uri(Constants.UserInfoEndpoint), accessToken);
                    var userInfoResponse = await userInfoClient.GetAsync();
Then I call    ClaimsIdentity cidentity = (ClaimsIdentity)claimsIdentity;
                    var loginResult = await GetLoginResultAsync(email, "123qwe", "xxx", cidentity);
                    CurrentUnitOfWork.SetTenantId(loginResult.Tenant.Id);
I am getting tenant id and user id from loginresult. But session user is always null.
How Can I get current user as current session user?
Visual studio 2015,.net frame work 4.7 and ABP version V2.1.3

**Comment by ismcagdas** [comment]
Have you tried injecting AbpSession and use it's properties ?
