### ISSUE TITLE
Issue while using AbpUserManager<Role, User>to set roles for user related to #269

### ISSUE THREAD

**Issue by jawadSharif** [aspnetboilerplate/module-zero-forsaken#406]
Hi Halil,
i have read the duplicate issue there but that answer does not fit my situation [https://github.com/aspnetboilerplate/module-zero/issues/269](url)
i am using it in ASPnetZero and encountering same problem 
in my case i'm using it in user app service and then getting this error.
i am unable to figure out if the lazy loading is enabled or not because i never disabled it myself,
and as its in an app service it should be under a unit of work automatically but i added that attribute to app service method but no luck.

**Comment by hikalkan** [comment]
Are you using EF core or EF 6.x? Can you share your stacktrace and ABP version.

**Comment by jawadSharif** [comment]
thanks for your reply
i am using EF6.x and following is the stacktrace as required

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Abp.Authorization.Users.AbpUserManager`3.d__67.MoveNext() in
D:\Halil\GitHub\module-zero\src\Abp.Zero\Authorization\Users\AbpUserManager.cs:line
631 --- End of stack trace from previous location where exception was
thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at
C0mpanyName.Pr0jectName.Authorization.Users.UserAppService.d__14.MoveNext()
in
D:\Projects\gulfstars\C0mpanyName.Pr0jectName\C0mpanyName.Pr0jectName.Application\Authorization\Users\UserAppService.cs:line
232 --- End of stack trace from previous location where exception was
thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at Abp.Threading.InternalAsyncHelper.d__1.MoveNext() in
D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line
40 --- End of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at
C0mpanyName.Pr0jectName.Authorization.Users.UserAppService.d__12.MoveNext()
in
D:\Projects\gulfstars\C0mpanyName.Pr0jectName\C0mpanyName.Pr0jectName.Application\Authorization\Users\UserAppService.cs:line
193 --- End of stack trace from previous location where exception was
thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at Abp.Threading.InternalAsyncHelper.d__1.MoveNext() in
D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line
40 --- End of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at Abp.Threading.InternalAsyncHelper.d__0.MoveNext() in
D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line
20 --- End of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Threading.Tasks.TaskHelpersExtensions.d__0.MoveNext() --- End of
stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End
of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Web.Http.Controllers.AuthenticationFilterResult.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown
--- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()


*Best Regards*



*Jawad Sharif*

Software Solution Provider
& Co-Founder

*BStreams Solutions*Contact: +92(322) 4439 221
URL: www.BStreamsSolutions.com


Note: This email will be considered as accepted and agreed upon if no reply
is received within 3 business days

**Comment by hikalkan** [comment]
Just try to call user.Roles.ToList() yourself in your application service method. And be sure that CurrentUnitOfWork is not null.

**Comment by jawadSharif** [comment]
yes i already tried with that user.Roles.ToList() and gives me same
exception.
and yes current unit of work is null i dont know why


*Best Regards*



*Jawad Sharif*

Software Solution Provider
& Co-Founder

*BStreams Solutions*Contact: +92(322) 4439 221
URL: www.BStreamsSolutions.com


Note: This email will be considered as accepted and agreed upon if no reply
is received within 3 business days

**Comment by acjh** [comment]
Is your method `public virtual`?

**Comment by hikalkan** [comment]
If this is an application service and you are using it via class reference, then you may need to make your method virtual (and add [UnitOfWork] attribute if necessary).
