### ISSUE TITLE
use Mysql in ABP Someting error occured in the package manage console

### ISSUE THREAD

**Issue by nikons5456** [aspnetboilerplate/module-zero-forsaken#407]
I want to use Mysql instead of Sql serser in ABP but when I Update -Database in the package manage console got the error Incorrect usage of spatial/fulltext/hash index and explicit index orderSo can anybody Help me？

**Comment by ismcagdas** [comment]
If you are using one of ABP templates, it's migration files are created for SQL Server.
So, just delete all migration files and use "Add-Migration" command to regenerate migrations for MySql.

**Comment by nikons5456** [comment]
But I still have the problem

**Comment by ismcagdas** [comment]
1. Do you use one of ABP templates ?
2. Does this happens out of the box or after you made some changes to project ?

**Comment by nikons5456** [comment]
Of course ! I download it from ![](https://aspnetboilerplate.com), In order to use Mysql,I changed the connectionString in web.config,Which just like this
`  <connectionStrings>
    <add name="Default" connectionString="Server=localhost; Database=MyWeb;port=3306; uid=root;password=123456" providerName="System.Data.SqlClient" />
  </connectionStrings>`
and I've installed the Nuget package named"MySql.Data.Entity",When I "Update-Database" in the Package Manage Console,It just told me that"Incorrect usage of spatial/fulltext/hash index and explicit index order",So is there something different between mysql and sql server,Or someting I did wrong?

**Comment by wenzel900** [comment]
Hi !
I'm using Mysql with the Pomelo.EntityFrameworkCore.MySql provider. It's all working fine

**Comment by ismcagdas** [comment]
@nikons5456 have you solved your problem ?

**Comment by agask2agask2** [comment]
I am having this problem right now did this ever get resolved.. what causes this?  it doesnt like the hash in my migrations.

**Comment by ismcagdas** [comment]
@agask2agask2 

* have you followed this document for using MySql https://aspnetboilerplate.com/Pages/Documents/EF-Core-MySql-Integration ?
* are you using Pomelo.EntityFrameworkCore.MySql provider or something else ?

**Comment by agask2agask2** [comment]
I'm actualy using EF6 with    these providers,
<provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.EntityFramework" />
    <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />

and the decorator over my context

 [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public class CoreContext : DbContext

it seems to work and connect and all..  but its generating a  "with hash" on the indexes when running migrations.   which MySQL doesn't like at least in the latest version I have..   what is with hash...?

**Comment by ismcagdas** [comment]
@agask2agask2 It seems like Pomelo doesn't have a provider for EF 6.x, see https://github.com/PomeloFoundation.

I haven't tried MySql.Data v8.0.11. You can downgrade to MySql.Data v6.9.11.
