### ISSUE TITLE
Prevent impersonation if that user is currently logged in?

### ISSUE THREAD

**Issue by kibria06cse** [aspnetboilerplate/module-zero-forsaken#419]
How can I prevent admin/or other users to impersonate a user, if that user is currently logged in? Or what can I do, if any user is impersonating another user and then that user is logged in the system, then all impersonated users will be logged out. How can I do it via asp.net boilerplate with MVC?

**Comment by hikalkan** [comment]
Hi,

This is a development question and you can do it in different ways. And this problem can be generalized and it's not much related to ABP. I suggest you to ask it in Stackowerflow.
