### ISSUE TITLE
asp.net core identityserver4 login error

### ISSUE THREAD

**Issue by xgd224743** [aspnetboilerplate/module-zero-forsaken#420]
hi,  
Reference Identity Server Integration document，
but login throw Exception:

````C#
System.InvalidOperationException: sub claim is missing
   at IdentityServer4.IdentityServerPrincipal.AssertRequiredClaims(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.<SignInAsync>d__7.MoveNext()
````

change login code: 
 
        [HttpPost]
        [UnitOfWork]
        public virtual async Task<JsonResult> Login(LoginViewModel loginModel, string returnUrl = "", string returnUrlHash = "")
        {
            returnUrl = NormalizeReturnUrl(returnUrl);
            if (!string.IsNullOrWhiteSpace(returnUrlHash))
            {
                returnUrl = returnUrl + returnUrlHash;
            } 

            var loginResult = await GetLoginResultAsync(loginModel.UsernameOrEmailAddress, loginModel.Password, GetTenancyNameOrNull());
           //change 
            loginResult.Identity.AddClaim(new Claim(JwtClaimTypes.Subject, loginResult.User.Id.ToString()));
            loginResult.Identity.AddClaim(new Claim(JwtClaimTypes.Name, loginResult.User.Name));
 
            await _signInManager.SignInAsync(loginResult.Identity, loginModel.RememberMe);
 
            await UnitOfWorkManager.Current.SaveChangesAsync();

            return Json(new AjaxResponse { TargetUrl = returnUrl });
        } 

login success,
Where setting is the error?

**Comment by ismcagdas** [comment]
Could it be related to https://github.com/IdentityServer/IdentityServer4/issues/1545 ?
