### ISSUE TITLE
AbpFeatureValueStore not registered

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero-forsaken#421]
I am still using 2.3.0. I recently implemented proper permission and role management (using AbpZero). But for some reason, AbpFeatureValueStore was not registered, because when getting a feature value, it always returned the default value for that feature, instead of the one written into the database. I tested this, and it seems the AbpFeatureValueStore was not registered to Dependency Injection.

If I manually register it in my core module with: IocManager.Register<IFeatureValueStore, AbpFeatureValueStore<Tenant, User>>(); It works.

Is this not supposed to be automatically registered somehow by AbpZero? Am I missing something which will startup AbpZero properly?

**Comment by acjh** [comment]
Note to maintainers: This is [based on the assumption](https://stackoverflow.com/questions/47383477/why-do-i-need-to-manually-register-abpfeaturevaluestore) that **Helper Interfaces** do what [the docs](https://aspnetboilerplate.com/Pages/Documents/Dependency-Injection#DocHelperInterfaces) implies.

> ## Helper Interfaces
>
> You may want to register a specific class that does not fit to conventional registration rules. ASP.NET Boilerplate provides **ITransientDependency** and **ISingletonDependency** interfaces as a shortcut. For example:
>
> ```c#
> public interface IPersonManager
> {
>     //...
> }
>
> public class MyPersonManager : IPersonManager, ISingletonDependency
> {
>     //...
> }
> ```
>
> In that way, you can easily register MyPersonManager. When need to inject a IPersonManager, MyPersonManager class is used. 

I [can't find](https://github.com/aspnetboilerplate/aspnetboilerplate/search?q=BasedOn) this non-conventional registrar. I traced [BasicConventionalRegistrar.cs](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/4cdf233b88187d1b2bdef58f568b3fc3afdda51f/src/Abp/Dependency/BasicConventionalRegistrar.cs) to its first appearance as [SimpleConventional*Registerer*.cs](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/26d45661b40a0016dd564b912f250b505c7103a6/src/Abp/Framework/Abp/Dependency/SimpleConventionalRegisterer.cs) (Jan 25, 2014) that registers `.WithService.DefaultInterfaces()`.

I also traced the related section in the docs from [Dependency-Injection.html](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/cb717170bfc8354b6953991ba3b9ba09cedb4544/doc/WebSite/Dependency-Injection.html#L279-L29) to its first appearance as a section in [dependency-injection.html](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/4b9b0bf87f3b1907d0c8b81f9d0a397a38e9e915/doc/WebSiteContents/dependency-injection.html#L302-L320) (Aug 17, 2014), but can't find a *registerer* [as of that commit](https://github.com/aspnetboilerplate/aspnetboilerplate/find/26d45661b40a0016dd564b912f250b505c7103a6) either.

**Comment by hikalkan** [comment]
Here is where we register IFeatureValueStore: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.ZeroCore/IdentityFramework/AbpZeroServiceCollectionExtensions.cs#L81

When you call AddAbpIdentity, it's automatically registered. Startup template calls AddAbp here: https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Core/Identity/IdentityRegistrar.cs#L17

Additional AddAbpTenantManager, AddAbpUserManager... calls in this code is to replace default services with custom ones and completely optional.

**Comment by Worthy7** [comment]
Where should I call this from then?
