### ISSUE TITLE
Host use of Features

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/module-zero-forsaken#422]
For building administrator pages, we may want to build pages which are basically the same as pages used by tenants, but just with a few extra "management" buttons on things.
So it somewhat makes sense that the Host users, may want to have certain "features" in use by the tenants.
For example, a user manager. In the Tenant version, users are entirely restricted at the DataFilter level to only be able to deal with users in their Tenant. At a host level, this is the same, but we have access to all Users instead.
The functionality inside the "user manager module" is the same, it's just DataFilter restricted depending on the users TenantId. But if I do want to enable the "user manager module" for my host, I can't, because a feature requires a TenantId.

I think Feature.TenantId should be nullable to allow for this scenario.

**Comment by hikalkan** [comment]
A better way would be to ignore feature check if this is a host user.

**Comment by Worthy7** [comment]
Hmm, I don't think that a host necessarily wants ALL the features of a system. As I said, what if there are multiple types of users on the host side?
What you are saying is basically that all hosts are always complete super-admins. Which I disagree with.

**Comment by acjh** [comment]
Feature is enabled per-tenant (or in this case, host). For multiple types of users, use role permission.

**Comment by Worthy7** [comment]
Ok I think that could work.
