### ISSUE TITLE
CreateOrMigrateForTenant not working

### ISSUE THREAD

**Issue by softcial** [aspnetboilerplate/module-zero-forsaken#423]
I'm having exactly the same issue as the one described in this other issue:
https://github.com/aspnetboilerplate/module-zero-forsaken/issues/226 

I know that that issue is closed but unfortunately the link provided by @ismcagdas is broken and can't find a sample on how to link the AbpZeroDbMigrator with the TenantContext.  Is there any available?

**Comment by hikalkan** [comment]
continue from https://github.com/aspnetboilerplate/module-zero-forsaken/issues/226
