### ISSUE TITLE
How to authenticate a single solution in two AbpApis? 

### ISSUE THREAD

**Issue by FilipeCavalcante** [aspnetboilerplate/module-zero-forsaken#425]
Here's my cenario:
I used to have two differents Abp bases solutions, front end, webapi, entity framework etc. Now i need to merge both frontend solution into a single one, but the webapi will remain separated. The merge part is done, and the login process is now working in one of Abp WebApi, and it's working just fine.

Now, as some requests will remain in a different webapi than the other one it was used to authenticate user, every request i made to this webapi returns an error saying that "the user did no login"

My question is, is there any way to shared "auth_token" between theses two webapi ?

Thanks in advance.

**Comment by hikalkan** [comment]
If you want to share auth tokens, consider a tool like identityserver, use a single server as auth authority.
