### ISSUE TITLE
Organization Unit - Role&Permission based

### ISSUE THREAD

**Issue by lnacosta91** [aspnetboilerplate/module-zero-forsaken#426]
Hey there! I'm struggling on how can I achieve next scenario:

**Current Model supports:**
User X has Role "Account Management" and he can create, edit and delete accounts.
User X belongs to OU "Financial Department" and he has access to all the accounts on the department.
User X can create, edit or delete all the accounts on the OU.

**What I need?**
The company decided to make a parallel department to manage accounts.
User Y is created with the role "Account Management" and he can create, edit and delete accounts.
A new OU is created for this second "Financial Department" and User Y has access to all the accounts on this department.
**How can I easy make the user Y be able to see all the accounts but not to be able to create, edit or delete accounts that belong to the other department?**

(Is not a real example but it describes the problem. I need to have an organization unit permission based system)

**Comment by ismcagdas** [comment]
@lnacosta91 I'm not sure if this is the best solution but, you can create new Permissions, for example [CanEditOtherOUAccounts], [CanDeleteOtherOUAccounts], [CanCreateOtherOUAccounts] (or just a single permission for checking 3 permissions). Then if user has these permissions, you can show related buttons. If user don't have this permissions you can filter the records like `usersOuIds.Contains(record.OrganizationUnitId)`.

In app service methods, you need to check these permissions in the code as well. You cannot add it to your app service methods as attributes. For example

```
public void DeleteAccount()
{
	var userOuIds = {Get this somehow}; // List<int>
	if(!IsGrantedAsync("CanCreateOtherOUAccounts") && !userOuIds.Contains(record.OrganizationUnitId)){
		// throw exception
	}
}
```

It is not the complete solution but I think you can use it roughly like this.

**Comment by lnacosta91** [comment]
Ok, I understood. But this will not work. If I have to do that in each method I will go crazy and the code will be not understandable.
My solution for now is to have a very good Organization Unit structure and relate it directly with roles and permissions.
The user can change his organization unit globally and all the roles and permissions will be updated.
In that way I just don't have to change the logic of the code, if not to make this kind of sub-tenancy at Organization Unit level... It would be cool if the framework support some kind of permission method override... Having the discrimination at both level, OU and roles can give you a lot of flexibility.

Anyway, thank you very much for the answer.

**Comment by ismcagdas** [comment]
@lnacosta91 you can change the framework level permission check logic by overriding the IsGrantedAsync method of PermissionChecker as well https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.ZeroCore/Authorization/PermissionChecker.cs#L41.

**Comment by lnacosta91** [comment]
End up going through other solution, thanks for the time and the advice.
