### ISSUE TITLE
How can I modify the Value field size(default is 2000) in AbpSettings table.

### ISSUE THREAD

**Issue by Noushida** [aspnetboilerplate/module-zero-forsaken#432]
migrationBuilder.AlterColumn<string>(
                  name: "Value",
                  table: "AbpSettings",
                  maxLength: 4000,
                  nullable: true,
                  oldClrType: typeof(string),
                  oldMaxLength: 2000,
                  oldNullable: true);

is it possible this way?

**Comment by maliming** [comment]
You can configure it under the `OnModelCreating` method.

https://docs.microsoft.com/en-us/ef/core/modeling/max-length#fluent-api

**Comment by Noushida** [comment]
Thanks for your response. Actually AbpSettings table is asp.net boiler
plate's entity. So I am getting a reference error in  OnModelCreating .

Thanks & Regards,
*Noushida K T*
Senior Software Engineer - Microsoft Technologies

[image: cid:ii_144d3e1003a21d10]
Ph: +91 484 4055006
USA | UAE | INDIA
www.fingent.com

**Comment by ismcagdas** [comment]
@Noushida could you share your code for OnModelCreating ? Setting entity is defined in Abp.Configuration namespace.
